BATCHES - groups of inputs 

The batches are used because:
1. We can calculate these things in parallel (bigger the batch more parallel operations could be done)
2. it helps with generalization.

In [6]:
import numpy as np

inputs1 = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2.0, 3.0, 0.5]


In [7]:
# we have to transpose the list of list to perform the dot product
# but the list of list cannot be transposed so we first convert it into a array
layer1_output = np.dot(inputs1, np.array(weights).T)+biases1
print(layer1_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Adding another layer, with same sizeas the previous layer

In [8]:
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1.0, 2.0, -0.5]

layer2_output = np.dot(layer1_output, np.array(weights2).T)+biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


Converting code to an OBJECT

In [9]:
# lets name the input as X with three samples
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

How we initialize a layer:
1. You have a saved trained model(i.e you have saved the weights and the biases) and you can load in that model itself.
2. Making a new neural network, we have to initiaize the weights and the biases. Weights can be initialised as random values in the rage of [-1,+1]. Smaller the range better the results. For biases we tend to initialize those as just 0, this helps us in checking for a dead network or if any of the neurons is giving the output as 0.



In [10]:
# Defining lets say 2 hidden layers
# n_inputs -- number of inputs
# n_neurons -- number of neurons in the layer
# weights are multiplied by 0.10 to limit the range btw [-1 to 1]
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [11]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)


In [13]:
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
