SOFTMAX ACTIVATION FUNCTION

1. Used in the output layer of the neural network, to make the output easier to interpret.
2. Accuracy is not a good indication of the model, but we have to find how wrong the model is actually(limitation of argmax activation function). Suppose two models predict the answers correctly, but one has large diff btw the correct result and other values, but in the second model the difference is not much. We can make a relative comparison between the different values produced by both the models.
3. This is why we do noy want to measure the accuracy, but want to known about what is the difference between the correct ans incorrect answers, we want that to be maximum so that a clear distinction between them is indicated.
4. The problem with previous activation functions is that the, each of the neurons are distinct i.e they dont have any relation between them to compare the values.
5. The next problem is that the outputs produced by previous activation functions are unbounded, so the relative closeness btw the values can vary between each of the sample that we have.
6. The softmax activation function transforms the raw outputs of the neural networks into a vector of probabilities.
7. Other activation functions can work fine in binary classification problems, not with multiclass problems(limitation of sigmoid activation function).
8. Limitation of ReLU function is that it clips the negative values to 0, there are cases where all the values can come out to be negative. Moreover no differentiation btw small and large negative values. Also during backprpogation learning from these clipped values has no meaning.
9. Applying softmax preserves the relative ordering of the raw output values.
10. One way to create this vector of probabilities is to take the value of neuron and divide it by the summation of all the values of other neurons in that layer. 



Why do we need another activation function ?
1. Bounding issue, no relation btw neurons, every neuron is exclusive, no good solid way of determining how wrong is this in any formal uniform way per sample that comes through.


Activation function:

1.   y = e^x (solves the negative values issue, while maintaining a scale of negative values)
2. But we need to normalize these exponential values to create a vector of probabilities, so to normalize we can divide each exponential value with the summation of exponential values of the output values. 


In [6]:
# # Using Basic Python
# import math

# layer_output = [4.8,1.21,2.385]
# E = math.e
# # E = 2.718281828459045

# exp_values = []
# for output in layer_output:
#     exp_values.append(E**output)

# print(exp_values)

# norm_base = sum(exp_values)
# norm_values = []

# for value in exp_values:
#     norm_values.append(value/norm_base)

# print(norm_values)
# print(sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [8]:
# # Using numpy
# import math
# import numpy as np
# import nnfs

# nnfs.init()

# layer_output = [4.8,1.21,2.385]
# E = math.e

# exp_values = np.exp(layer_output)
# norm_values = exp_values/np.sum(exp_values)

# print(norm_values)
# print(sum(norm_values))


[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [16]:
# Using numpy for a batch of input
import math
import numpy as np
import nnfs

nnfs.init()

layer_output = [[4.8,1.21,2.385],
                [8.9,-1.81,0.2],
                [1.41,1.051,0.026]]

exp_values = np.exp(layer_output)
print(exp_values)

#print(np.sum(layer_output,axis=1,keepdims=True)) 
# got our required sums list in a 1X3 format

norm_values = exp_values / np.sum(exp_values,axis=1,keepdims=True)

print(norm_values)


[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


1. Small problem with exp function is that the numbers increase massively, and soon can go out of the bounds
2. One way to solve this is to take the maximum of the raw output values and subtract each value from this maximum value. This will limit our final output in the range of [0,1]

In [18]:
# FINAL CODE 
import numpy as np 
import nnfs
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data  

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
        self.output = probabilities

X,y = spiral_data(samples=100,classes=3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33335656 0.33332282 0.33332065]
 [0.3333794  0.33331248 0.3333082 ]
 [0.33340728 0.3332996  0.3332931 ]
 [0.3334332  0.33328772 0.33327907]]
